
#include "weights.hpp"


Weights::Weights()
{
    // Fill table from the static constants
    aW[HAS_CASTLED]          = HAS_CASTLED_WGHT;
    aW[CAN_CASTLE]           = CAN_CASTLE_WGHT;
    aW[ISOLANI]              = ISOLANI_WGHT;
    aW[ISOLANI_ROOK]         = ISOLANI_ROOK_WGHT;
    aW[PAWN_HOLE]            = PAWN_HOLE_WGHT;
    aW[KNIGHT_HOLE]          = KNIGHT_HOLE_WGHT;
    aW[DOUBLED]              = DOUBLED_WGHT;
    aW[DOUBLED_ROOK]         = DOUBLED_ROOK_WGHT;
    aW[DOUBLED_OPEN_FILE]    = DOUBLED_OPEN_FILE_WGHT;
    aW[PASSED_PAWN_SLOPE]    = PASSED_PAWN_SLOPE_WGHT;
    aW[PASSED_PAWN_YINRCPT]  = PASSED_PAWN_YINRCPT_WGHT;
    aW[PAWN_ON_CTR_DEF]      = PAWN_ON_CTR_DEF_WGHT;
    aW[PAWN_ON_CTR_OFF]      = PAWN_ON_CTR_OFF_WGHT;
    aW[PAWN_ON_ADV_CTR]      = PAWN_ON_ADV_CTR_WGHT;
    aW[PAWN_ON_ADV_FLK]      = PAWN_ON_ADV_FLK_WGHT;
    aW[KNIGHT_ON_CTR]        = KNIGHT_ON_CTR_WGHT;
    aW[BISHOP_ON_CTR]        = BISHOP_ON_CTR_WGHT;
    aW[TWO_BISHOPS]          = TWO_BISHOPS_WGHT;
    aW[QUEEN_OUT_EARLY]      = QUEEN_OUT_EARLY_WGHT;
    aW[BISHOP_PATTERN]       = BISHOP_PATTERN_WGHT;
    aW[F_PAWN_MOVED_EARLY]   = F_PAWN_MOVED_EARLY_WGHT;
    aW[ROOK_CONNECTED]       = ROOK_CONNECTED_WGHT;
    aW[ROOK_ON_OPEN_FILE]    = ROOK_ON_OPEN_FILE;
    aW[KING_ON_FILE]         = KING_ON_FILE_WGHT;
    aW[MAJOR_ON_RANK7]       = MAJOR_ON_RANK7_WGHT;
    aW[MAJOR_ON_RANK8]       = MAJOR_ON_RANK8_WGHT;
    aW[KNIGHT_ON_EDGE]       = KNIGHT_ON_EDGE_WGHT;
    aW[KING_EDGE]            = KING_EDGE_WGHT;
    aW[KINGS_CLOSE_TOGETHER] = KINGS_CLOSE_TOGETHER_WGHT;
    aW[ATTACKERS_ON_KING]    = ATTACKERS_ON_KING_WGHT;
    aW[CENTER_OCCUPY_PIECES] = CENTER_OCCUPY_PIECES_WGHT;
    aW[DEVELOPMENT_OPENING]  = DEVELOPMENT_OPENING;
}
